In [ ]:
12

12

In [ ]:
type(12) #koji tip je varijabla 12 - int cijeli brojevi

int

In [ ]:
type(12.5)

float

In [ ]:
type('lana') #mogu se koristiti mali ili veliki navodnici isto je

str

In [ ]:
"lana"

'lana'

In [ ]:
3 < 2 #bulian

False

In [ ]:
#Organizacija podataka
dictionary = {}
list = []
tuple = ()

SyntaxError: invalid syntax (ipython-input-2447218258.py, line 2)

In [ ]:
type[1, 2, 3]

type[1, 2, 3]

In [ ]:
type([1, 2, 3])

list

In [ ]:
t = [1, 2, 3]

In [ ]:
t

[1, 2, 3]

In [ ]:
plants = ["apple": "pear", "banana": "a hearb"]

In [ ]:
type({"apple": "pear", "banana": "a hearb"})

dict

In [ ]:
import pandas as pd

In [ ]:
pd.dataframe(plants, [0, 1])

AttributeError: module 'pandas' has no attribute 'dataframe'

In [ ]:
squares = [1, 4, 9, 16, 25]

In [ ]:
type(squares)

list

In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
squares[4] #indeks 4 znaci na 4 mjestu je broj 25 jer beoji od 0

25

In [ ]:
squares[-2] #ide se od iza

16

In [ ]:
squares[:] #raspon valjda od kud do kud zelimo da se pokaze lista

[1, 4, 9, 16, 25]

In [ ]:
squares[1:] #od prvog do kraja

[4, 9, 16, 25]

In [ ]:
squares[1:3] #prvi ukljucen zadnji ne

[4, 9]

In [ ]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
sq2 = squares + [36, 49, 64, 81, 100]

In [ ]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
animals = ["cat", "dog", "bird"]

In [ ]:
animals[0]

'cat'

In [ ]:
len(sq2)

10

In [ ]:
len(sq2[:5])

5

In [ ]:
letters = ["a", "b", "c", "d", "e", "f", "g"]

In [ ]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [ ]:
letters[1:2] = [1, 2, 3, 4, 5]
letters

['a', 1, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [ ]:
len(letters)

11

In [ ]:
abs(1)

1

In [ ]:
abs(-10) #apsolutni broj

10

In [ ]:
import operator as op

In [ ]:
1 +3

4

In [ ]:
operator.add(1, 3)

4

In [ ]:
operator.sub(1, 10)

-9

In [ ]:
operator.eq(1, 10)

False

In [ ]:
operator.eq(10, 10)

True

#Print

In [ ]:
print(1)

1


In [ ]:
print("This is Sparta!")

This is Sparta!


In [ ]:
print("this" + "is" + "Sparta" + "!")

thisisSparta!


In [ ]:
print("This" + " " + "is" + " " + "Sparta" + " " + "!")

This is Sparta !


In [ ]:
print("This", "is", "Sparta", "!") #ako su zarezi ne moramo radit razmake

This is Sparta !


In [ ]:
print(sq2[1:5])

[4, 9, 16, 25]


In [ ]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
type(None)

NoneType

In [ ]:
def our_function(x):
  """This function multiplies its argument by 2.
  Writen by Jakov"""
  Result = x*2
  return Result

In [ ]:
our_function(5)

10

In [ ]:
our_function(3.12)

6.24

In [ ]:
type(our_function)

function

In [ ]:
import math as mt

In [ ]:
def ph(c):
  """This function calculates th pH of a solution.
  It uses the concentration of the H+ in mol/L"""
  ph_value = -mt.log10(c)
  return ph_value

In [ ]:
ph(0.001)

3.0

In [ ]:
def task(x, y):
  """definicija"""
  print("This is a log10 of x", mt.log10(x))
  print("This is a log10 of y", mt.log10(y))
  new_number = mt.log10(x) + mt.log10(y)
  print("The resault is below:")
  return new_number




In [ ]:
task(2,5)

This is a log10 of x 0.3010299956639812
This is a log10 of y 0.6989700043360189
The resault is below:


1.0

In [ ]:
def konv_eur(euro):
  dkk = euro*7.55
  return dkk

In [ ]:
konv_eur(10)

75.5

In [ ]:
def plus(a, b, c, d):
  suma = a+b+c+d
  return suma

In [ ]:
plus(3, 4, 5, 6)

18

In [ ]:
# = označava assigment a == označava jednakost u pravom smislu riječi
1 == 1

True

In [ ]:
k = (5, 2, 3)

In [ ]:
k == (1, 2, 3)

False

In [ ]:
width = 20
height = 5*90
height, width

(450, 20)

In [ ]:
width == 30

True

In [ ]:
width == 20

False

In [ ]:
width = 30 #dodjelili novi broj

In [ ]:
cp1 = "Tomo"
cp2 = "Marija"
cp1, cp2

('Tomo', 'Marija')

In [ ]:
width == height

False

In [ ]:
width = height

In [ ]:
width == height

True

In [ ]:
width

450

In [ ]:
cp1 == cp2

False

In [ ]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5


True

In [ ]:
width is height

True

In [ ]:
width is not height

False

In [ ]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [ ]:
squares.append(36)

In [ ]:
squares

[1, 4, 9, 16, 25, 36]

In [ ]:
squares_part2 = squares + [36]
squares_part2

[1, 4, 9, 16, 25, 36, 36]

In [ ]:
new_list.append(49) #new_list nije definirana

NameError: name 'new_list' is not defined

In [ ]:
last_list = squares.copy()
last_list

[1, 4, 9, 16, 25, 36]

In [ ]:
squares.append(10)
last_list

[1, 4, 9, 16, 25, 36]

In [ ]:
squares

[1, 4, 9, 16, 25, 36, 10]

In [ ]:
print("Participants in the course were", cp1, "and", cp2)


Participants in the course were Tomo and Marija


In [ ]:
print ("Participants in the course were %s and %s."
      %(cp1, cp2))


Participants in the course were Tomo and Marija.


In [ ]:
sample = "u552"
conc = 0.02

print("In a sample %s we found %s ml/L od drugs" %(sample, conc))

In a sample u552 we found 0.02 ml/L od drugs


In [ ]:
print(f"In a sample {sample} we found ")

In a sample u552 we found 


In [ ]:
def bmi(w, h):
  bmi = w/h **2
  return bmi

In [ ]:
bmi(90, 1.82)

27.17063156623596

In [ ]:
#c1 * v1 = c2 * v2

In [ ]:
def diluter(c1=0.5, v1=1, v2=2): #moze se definirat vrijednos i odmah pri definiranju funkcije
  """Calculating  dilution
  returns c2"""
  c2 = c1*v1/v2
  return diluter

In [ ]:
diluter(0.5, 1, 2)

<function __main__.diluter(c1=0.5, v1=1, v2=2)>

In [ ]:
help(diluter)

In [ ]:
diluter(2)

<function __main__.diluter(c1=0.5, v1=1, v2=2)>

In [ ]:
diluter(1,5,12)

<function __main__.diluter(c1=0.5, v1=1, v2=2)>

In [ ]:
def factor_corrections(c, f=1):
  conc = c*f
  return conc

In [ ]:
factor_corrections(0.002)

0.002

In [ ]:
def do_something_else(a=1, b=2, c=3):
  return (a, b, c)

In [ ]:
do_something_else(10, 10)

(10, 10, 3)

In [ ]:
do_something_else()

(1, 2, 3)

In [ ]:
do_something_else(5, 5, c=5)

(5, 5, 5)

In [ ]:
do_something_else(a=10) #bitno je što je prvo definirano

(10, 2, 3)

In [ ]:
def suma(a, b):
  return a+b

In [ ]:
def addding_3rd(a,b,c):
  return suma(a,b)+c

In [ ]:
addding_3rd(1,2,3)

6

#for

In [ ]:
my_friends = ["Matija", "lovro", "Dino", "Luka"]

In [ ]:
for x in my_friends:
  print(x)

Matija
lovro
Dino
Luka


In [ ]:
weigths = [80, 55, 90, 82]
heights = [1.8, 1.6, 1.9, 1.85]

for x, friend in enumerate(my_friends):
  bmi_person = bmi(weigths[x], heights[x])
  print(f"The BMI of {friend} is {bmi_person}")

The BMI of Matija is 24.691358024691358
The BMI of lovro is 21.484374999999996
The BMI of Dino is 24.930747922437675
The BMI of Luka is 23.959094229364496


In [ ]:
print(f"{friend} has the bmi of {bmi_person}")

Luka has the bmi of 23.959094229364496


In [ ]:
squares = [1, 4, 9, 16, 25]


In [ ]:
for x in squares:
  print("Element is %s" %x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25


In [ ]:
for number in squares:
  print(number)


1
4
9
16
25


In [ ]:
course_participants = [cp1, cp2]


In [ ]:
course_participants

['Tomo', 'Marija']

In [ ]:
for n in course_participants:
  print(n)

Tomo
Marija


In [ ]:
for pos in range(len(course_participants)):
  print(pos)


0
1


In [ ]:
for number, element in enumerate(squares):
  print(number, element)

0 1
1 4
2 9
3 16
4 25


In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
import math

In [ ]:
for number in squares:
  sq_root = math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0


#if else
=
==
<
>
<=
>=
=!=

In [ ]:
1 <= 2

True

In [ ]:
if 1 == 2:
  print("yes")
  print("da")
  print("daaa")

In [ ]:
1 == 2

False

In [ ]:
cp1 = "Mila"
cp2 = "Marko"


In [ ]:
if cp1 == cp2:
  print("da")

In [ ]:
if cp1 != cp2:
  print("da")

da


In [ ]:
if cp1 == cp2:
  print("da")
else:
  print("ne")

ne


In [ ]:
def check_gender_by_name(name):
  if name[-1]=="a":
    gender = "female"
  elif name[-1]=="o":
    gender = "male"
  else:
    gender = "unknown"
  return gender



In [ ]:
check_gender_by_name("Marko")

'male'

In [ ]:
check_gender_by_name("Marija")

'female'

In [ ]:
check_gender_by_name("petar")

'unknown'

In [ ]:
import math as m

In [ ]:
def ph(c):
  return -m.log10(c)

In [ ]:
ph(0.03)

1.5228787452803376

In [ ]:
def ph_evaluator(c=0.001):
  """ph decision maker"""
  ph_value = ph(c)

  if ph_value < 7:
    decision = kiselo
  else:
    decision = "lužnato"

  return decision
  ph_evaluator()

In [ ]:
def ph_evaluator(c=0.001):
  if ph(c) < 7:
    return "kiselo"
  else:
    return "lužnato"

conc_list = [0.001, 0.01, 0.1, 1, 10]
for solution in conc_list:
  print(ph_evaluator(solution))


kiselo
kiselo
kiselo
kiselo
kiselo


In [ ]:
def test_if_else(a, b):
  """a i b su argumenti
return "a > b" or "a is not > b"""

  if a > b:
    print(a, " > ", b)
  else:
    print("%d is not > %d" %(a, b))

In [ ]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a i b su argumenti
    return "a > b" or "a is not > b



In [ ]:
def rectangle_area(a, b):
  """dokumentacija"""
  A = a*b
  if a == b:
    print("kvadrat")
  else:
    print("pravokutnik")
  return A

In [ ]:
for letter in [1, 2, 3]:
  print("broj: ", letter)

broj:  1
broj:  2
broj:  3


In [ ]:
x =5

In [ ]:
x

5

In [ ]:
x = 7

In [ ]:
x

7

In [ ]:
y = 2

In [ ]:
x + y

9

In [ ]:
površina = rectangle_area(5, 4)


pravokutnik


In [ ]:
površina

20

In [ ]:
-(3**4)


-81

In [ ]:
3 * 3.75 / 1.5

7.5

In [ ]:
a = [4, 5, 6]
n = [1, 2, 3]


In [ ]:
x = [a, n]

In [ ]:
x

[[4, 5, 6], [1, 2, 3]]

In [ ]:
import numpy as np

In [ ]:
nums1 = [1, 2, 3, 4, 5]
nums1

[1, 2, 3, 4, 5]

In [ ]:
nums2 = np.array(nums1)

In [ ]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [ ]:
max(nums1)

5

In [ ]:
min(nums1)

1

In [ ]:
np.min(nums1)

np.int64(1)

In [ ]:
x1 = np.array([1.3, 0, 2])

In [ ]:
x1

array([1.3, 0. , 2. ])

In [ ]:
x2 = np.array([1, 0, 2])

In [ ]:
x2

array([1, 0, 2])

In [ ]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [ ]:
x2.dtype

dtype('int64')

In [ ]:
x1.dtype

dtype('float64')

In [ ]:
x2 = np.arange(20, 50, 2)
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
np.linspace(10, 20, 10, endpoint=True)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
nule = np.zeros((5, 3))
nule.shape

(5, 3)

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x4 = np.random.random((3, 10))
x4

array([[0.46666982, 0.90867687, 0.64873379, 0.56172023, 0.0424514 ,
        0.45637128, 0.94594886, 0.67702472, 0.96616586, 0.06755013],
       [0.40831926, 0.76869752, 0.61664887, 0.1821391 , 0.98077298,
        0.90057681, 0.81945945, 0.08814828, 0.50680062, 0.08936388],
       [0.20848624, 0.39624643, 0.85476927, 0.05397292, 0.88703229,
        0.4006225 , 0.95779903, 0.67571846, 0.14621146, 0.19714492]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.466670  0.908677  0.648734  0.561720  0.042451  0.456371  0.945949   
1  0.408319  0.768698  0.616649  0.182139  0.980773  0.900577  0.819459   
2  0.208486  0.396246  0.854769  0.053973  0.887032  0.400622  0.957799   

          7         8         9  
0  0.677025  0.966166  0.067550  
1  0.088148  0.506801  0.089364  
2  0.675718  0.146211  0.197145

In [ ]:
x4.shape

(3, 10)

In [ ]:
x4.dtype

dtype('float64')

In [ ]:
x4.reshape(10, 3)

array([[0.46666982, 0.90867687, 0.64873379],
       [0.56172023, 0.0424514 , 0.45637128],
       [0.94594886, 0.67702472, 0.96616586],
       [0.06755013, 0.40831926, 0.76869752],
       [0.61664887, 0.1821391 , 0.98077298],
       [0.90057681, 0.81945945, 0.08814828],
       [0.50680062, 0.08936388, 0.20848624],
       [0.39624643, 0.85476927, 0.05397292],
       [0.88703229, 0.4006225 , 0.95779903],
       [0.67571846, 0.14621146, 0.19714492]])

In [ ]:
x4.T

array([[0.46666982, 0.40831926, 0.20848624],
       [0.90867687, 0.76869752, 0.39624643],
       [0.64873379, 0.61664887, 0.85476927],
       [0.56172023, 0.1821391 , 0.05397292],
       [0.0424514 , 0.98077298, 0.88703229],
       [0.45637128, 0.90057681, 0.4006225 ],
       [0.94594886, 0.81945945, 0.95779903],
       [0.67702472, 0.08814828, 0.67571846],
       [0.96616586, 0.50680062, 0.14621146],
       [0.06755013, 0.08936388, 0.19714492]])

In [ ]:
np.arange(2, 20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [ ]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A = np.arange(2, 5)
A

array([2, 3, 4])

In [ ]:
I@A

array([2., 3., 4.])

In [ ]:
A@A

np.int64(29)